import { useState, useMemo } from 'react'
import { AlertCircle, ChevronDown, ChevronUp, ExternalLink } from 'lucide-react'

// Fund data generated by: npm run fund-data
// Source: SEC EDGAR Form D + CalPERS PE Fund Performance
import FUND_DATA from '../data/fund-data.json'

// ── Brand palette ─────────────────────────────────────────────────────────────
const COLOR_DEPLOYED   = '#2D3068'  // Space Blue  — deployed capital
const COLOR_RESERVES   = '#8B9FD4'  // Ultraviolet light — reserves
const COLOR_DRY_POWDER = '#E5E7EB'  // Gray — undeployed / dry powder

const SECTOR_CFG = {
  Fiber:     { color: '#B8744F', label: 'Fiber' },
  Cable:     { color: '#2D3068', label: 'Cable' },
  Wireless:  { color: '#00DEC8', label: 'Wireless' },
  Satellite: { color: '#5872E0', label: 'Satellite' },
  Other:     { color: '#aeaeb2', label: 'Other' },
}
const SECTORS = Object.keys(SECTOR_CFG)

// ── Helpers ───────────────────────────────────────────────────────────────────

// Longest-first so "XIII" matches before "III", "XIV" before "IV", etc.
const ROMAN = ['XVIII','XVII','XVI','XV','XIV','XIII','XII','XI','VIII','VII','VI','IX','IV','III','II','X','V','I']

function extractFundNum(name) {
  if (!name) return null
  for (const r of ROMAN) {
    if (new RegExp(`\\b${r}\\b`, 'i').test(name)) return r.toUpperCase()
  }
  const m = name.match(/\b(\d+)\b/)
  return m ? m[1] : null
}

function getSector(type) {
  if (!type) return 'Other'
  if (['Pure Fiber (FTTH)','CLEC / Fiber','ILEC / Fiber','Fiber Infrastructure REIT',
       'Fiber ISP (MDU/HOA)','Enterprise Fiber / Carrier','Fixed Wireless','ILEC / DSL']
      .some(t => type === t || type.startsWith(t.split(' ')[0]))) return 'Fiber'
  if (type.startsWith('MSO'))  return 'Cable'
  if (type.startsWith('MNO'))  return 'Wireless'
  if (type.includes('Satellite') || type.startsWith('DBS')) return 'Satellite'
  return 'Other'
}

const fmtB = (v, est = false) => {
  if (v == null) return '—'
  const p = est ? '~' : ''
  if (v >= 1e9) return `${p}$${(v / 1e9).toFixed(1)}B`
  if (v >= 1e6) return `${p}$${(v / 1e6).toFixed(0)}M`
  return `${p}$${v.toLocaleString()}`
}
const fmtM = (m, est = false) => (m == null ? '—' : fmtB(m * 1e6, est))

/**
 * Estimate % of capital deployed based on fund vintage year.
 * Calibrated to typical infrastructure fund deployment pace
 * (slower than PE buyout — infra funds hold assets 7-15 yrs).
 */
function estDeployedPct(vintage) {
  if (!vintage) return null
  const age = 2026 - vintage
  if (age >= 7) return 0.94
  if (age >= 6) return 0.88
  if (age >= 5) return 0.80
  if (age >= 4) return 0.70
  if (age >= 3) return 0.56
  if (age >= 2) return 0.38
  if (age >= 1) return 0.20
  return 0.08
}

// Check if a Form D entity name corresponds to a primary fund name
function formDMatchesFund(fundName, entityName) {
  if (!fundName || !entityName) return false
  const n1 = extractFundNum(fundName)
  const n2 = extractFundNum(entityName)
  if (!n1 || !n2 || n1 !== n2) return false
  // Firm first word must appear in entity name
  const firmWord = fundName.split(/\s+/)[0].toLowerCase()
  return entityName.toLowerCase().includes(firmWord)
}

// Strictly match a CalPERS entry to a primary fund — must share fund number
// AND firm first word, and not be an obvious false positive
function calpersMatchesFund(fundName, calpersName, firmFirstWord) {
  if (!fundName || !calpersName) return false
  const n1 = extractFundNum(fundName)
  const n2 = extractFundNum(calpersName)
  if (!n1 || !n2 || n1 !== n2) return false
  if (!calpersName.toLowerCase().includes(firmFirstWord.toLowerCase())) return false
  // Exclude obvious false positives
  const cn = calpersName.toLowerCase()
  if (cn.includes('healthcare') || cn.includes('hc/ft') || cn.includes('oaktree') ||
      cn.includes('real estate') || cn.includes('accel-kkr')) return false
  return true
}

// ── Data builder ──────────────────────────────────────────────────────────────

function buildFundRows(deals) {
  // Build firm → ISP deals map
  const firmDeals = new Map()
  deals.forEach(d => {
    const addPE = (pe, role) => {
      if (!pe?.firm) return
      if (!firmDeals.has(pe.firm)) firmDeals.set(pe.firm, [])
      const list = firmDeals.get(pe.firm)
      if (!list.find(x => x.id === d.id)) {
        const targetType = role === 'acquirer' ? d.acquired?.type : d.acquirer?.type
        list.push({
          id: d.id, date: d.date, status: d.status,
          dealValue: d.dealValue,
          acquirerName: d.acquirer?.name,
          targetName:   d.acquired?.name,
          role,
          sector: getSector(targetType),
        })
      }
    }
    addPE(d.acquirer?.pe, 'acquirer')
    addPE(d.acquired?.pe, 'target')
  })

  const rows = []

  FUND_DATA.firms.forEach(firmEntry => {
    const allFirmDeals = (firmDeals.get(firmEntry.firmRaw) ?? [])
      .filter(d => d.status !== 'Terminated')
    const primaryFunds = firmEntry.dealsData?.primaryFunds ?? []
    if (!primaryFunds.length) return

    const firmFirstWord = (firmEntry.firmNames?.[0] ?? firmEntry.firmRaw).split(/\s+/)[0]

    primaryFunds.forEach(fundName => {
      // ── Form D match ──────────────────────────────────────────────────────
      const formDMatch = (firmEntry.secEdgar?.formD ?? [])
        .filter(f => f.totalAmountSold > 0 && formDMatchesFund(fundName, f.entityName))
        .sort((a, b) => b.totalAmountSold - a.totalAmountSold)[0] ?? null

      // ── CalPERS match (strict) ────────────────────────────────────────────
      const calpersMatch = (firmEntry.calpers ?? [])
        .filter(c => calpersMatchesFund(fundName, c.fundName, firmFirstWord))
        .sort((a, b) => (b.committed ?? 0) - (a.committed ?? 0))[0] ?? null

      // ── Core metrics ──────────────────────────────────────────────────────
      const committedM = formDMatch?.totalAmountSold
        ? formDMatch.totalAmountSold / 1e6
        : null

      // Vintage: CalPERS first, then Form D filing year - 1 (filed after first close)
      const vintage = calpersMatch?.vintage
        ?? (formDMatch?.filingDate ? parseInt(formDMatch.filingDate.slice(0, 4)) - 1 : null)

      const deployedPct  = estDeployedPct(vintage)
      const estDeployedM = committedM && deployedPct != null ? committedM * deployedPct : null
      const estReservesM = committedM ? committedM * 0.10 : null  // ~10% reserved for follow-ons
      const estDryPwdrM  = committedM && estDeployedM != null
        ? Math.max(committedM - estDeployedM - (estReservesM ?? 0), 0)
        : null

      // ISP deployed: divide firm's total ISP across all primary funds (equal-weight proxy)
      const ispDeployedM = allFirmDeals.reduce((s, d) => s + (d.dealValue ?? 0), 0)
        / Math.max(primaryFunds.length, 1) / 1e6

      // For co-lead firms (firmRaw contains '/' or '+'), derive firmDisplay
      // from the fund name when the fund's first word doesn't match the co-lead's primary firm.
      // e.g. "Pamlico Capital Fund VI" under "Oak Hill Capital + Pamlico Capital" → "Pamlico Capital"
      const rawFirmDisplay = firmEntry.firmNames?.[0] ?? firmEntry.firmRaw
      const isCoLead = firmEntry.firmRaw.includes('/') || firmEntry.firmRaw.includes('+')
      let firmDisplay = rawFirmDisplay
      if (isCoLead) {
        const fundFW  = fundName.split(/\s+/)[0].toLowerCase()
        const dispFW  = rawFirmDisplay.split(/\s+/)[0].toLowerCase()
        if (!fundFW.startsWith(dispFW) && !dispFW.startsWith(fundFW)) {
          // Fund belongs to a different entity than the primary display firm
          firmDisplay = fundName.split(/\s+/).slice(0, 2).join(' ')
        }
      }

      rows.push({
        key:         `${firmEntry.firmRaw}::${fundName}`,
        fundName,
        firmRaw:     firmEntry.firmRaw,
        firmDisplay,
        vintage,
        committedM,
        estDeployedM,
        estReservesM,
        estDryPwdrM,
        deployedPct,
        ispDeployedM,
        formDData:   formDMatch,
        calpersData: calpersMatch,
        deals:       allFirmDeals,
        hasSize:     !!committedM,
        isEstimated: !!(committedM && deployedPct != null),
      })
    })
  })

  // ── Deduplicate: merge rows that resolve to the same fund ─────────────────────
  // Key: fundName-first-word + fund number (not firmRaw) so that co-lead entries
  // (e.g. "DigitalBridge Group / Crestview Partners") collapse with the single-firm
  // entry (e.g. "Crestview Partners") that lists the same fund.
  // Examples that now deduplicate correctly:
  //   "Crestview Partners IV" from two firmEntries   → crestview::IV
  //   "Oak Hill Capital Partners V" from two entries  → oak::V
  //   "Stonepeak Infrastructure Partners IV" vs "Stonepeak Infrastructure Fund IV" → stonepeak::IV
  // Family-owned / non-numbered funds still collapse by firmRaw.
  const seen = new Map()
  const dedupedRows = []
  for (const row of rows) {
    const fundNum      = extractFundNum(row.fundName)
    const fundFirstWord = row.fundName.split(/\s+/)[0].toLowerCase()
    // When fundNum is null (no roman/arabic numeral), collapse by firmRaw alone
    const dedupeKey = fundNum
      ? `${fundFirstWord}::${fundNum}`
      : `${row.firmRaw}::_nofund_`
    if (!seen.has(dedupeKey)) {
      seen.set(dedupeKey, row)
      dedupedRows.push(row)
    } else {
      // Merge: prefer the entry with more data (committedM, calpersData)
      const existing = seen.get(dedupeKey)
      if (!existing.committedM && row.committedM) Object.assign(existing, row, { key: existing.key })
      else if (!existing.calpersData && row.calpersData) existing.calpersData = row.calpersData
      // Merge ISP deals (union by id)
      const dealIds = new Set(existing.deals.map(d => d.id))
      for (const d of row.deals) {
        if (!dealIds.has(d.id)) existing.deals.push(d)
      }
      existing.ispDeployedM = existing.deals.reduce((s, d) => s + (d.dealValue ?? 0), 0) / 1e6
    }
  }

  // Sort: largest committed first, then by ISP deployed
  return dedupedRows.sort((a, b) =>
    (b.committedM ?? b.ispDeployedM ?? 0) - (a.committedM ?? a.ispDeployedM ?? 0)
  )
}

// Build sector-lean data for the right panel (from all firm-level deals)
function buildSectorLean(deals) {
  const map = {}
  let total = 0
  deals.forEach(d => {
    const addPE = (pe, role) => {
      if (!pe?.firm) return
      const tType = role === 'acquirer' ? d.acquired?.type : d.acquirer?.type
      const s = getSector(tType)
      map[s] = (map[s] ?? 0) + (d.dealValue ?? 0)
      total += (d.dealValue ?? 0)
    }
    if (d.status === 'Terminated') return
    addPE(d.acquirer?.pe, 'acquirer')
    addPE(d.acquired?.pe, 'target')
  })
  return SECTORS.map(name => ({
    name,
    value: map[name] ?? 0,
    pct: total > 0 ? (map[name] ?? 0) / total : 0,
  })).filter(s => s.value > 0).sort((a, b) => b.value - a.value)
}

// ── KPI Card ──────────────────────────────────────────────────────────────────

function KPICard({ title, value, sub, badge }) {
  return (
    <div style={{
      background: '#fff', borderRadius: 12,
      border: '1px solid rgba(0,0,0,0.07)',
      padding: '18px 20px', flex: 1, minWidth: 0,
    }}>
      <p style={{ fontSize: 12, color: 'var(--ink-4)', fontWeight: 500, marginBottom: 8, lineHeight: 1.3 }}>
        {title}
      </p>
      <p style={{ fontSize: 26, fontWeight: 700, color: 'var(--ink-1)', lineHeight: 1, marginBottom: 4 }}>
        {value}
      </p>
      {sub   && <p style={{ fontSize: 12, color: 'var(--ink-3)', lineHeight: 1.4 }}>{sub}</p>}
      {badge && <p style={{ fontSize: 11, color: '#B8744F', marginTop: 5, fontWeight: 500 }}>⚠ {badge}</p>}
    </div>
  )
}

// ── Fund Card ─────────────────────────────────────────────────────────────────

function FundCard({ fund, onNavigate }) {
  const [open, setOpen] = useState(false)

  // Top-right metric: dry powder > committed size > ISP deployed
  const metric = fund.estDryPwdrM != null
    ? { value: fmtM(fund.estDryPwdrM, true), label: 'est. dry powder', valueColor: '#2D3068' }
    : fund.committedM != null
      ? { value: fmtM(fund.committedM),       label: 'fund size (EDGAR)', valueColor: '#2D3068' }
      : { value: fmtM(fund.ispDeployedM),     label: 'ISP deployed',      valueColor: '#B8744F' }

  // Bar proportions (relative to committedM, or 5× ISP if no size)
  const barBase       = fund.committedM ?? (fund.ispDeployedM * 5)
  const deployedFrac  = fund.estDeployedM  != null && barBase > 0 ? fund.estDeployedM  / barBase : null
  const reservesFrac  = fund.estReservesM  != null && barBase > 0 ? fund.estReservesM  / barBase : null
  const ispFrac       = barBase > 0 ? Math.min(fund.ispDeployedM / barBase, 1) : 0

  return (
    <div style={{
      background: '#fff', borderRadius: 12,
      border: '1px solid rgba(0,0,0,0.07)',
      padding: '18px 20px 14px',
    }}>
      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <div
        onClick={() => setOpen(o => !o)}
        style={{ display: 'flex', alignItems: 'flex-start', gap: 16, cursor: 'pointer', marginBottom: 12 }}
      >
        <div style={{ flex: 1, minWidth: 0 }}>
          <p style={{
            fontSize: 15, fontWeight: 700, color: 'var(--ink-1)', lineHeight: 1.25,
            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
          }}>
            {/* Hide "N/A" fund names — use firm type descriptor instead */}
            {fund.fundName === 'N/A' || fund.fundName?.startsWith('N/A')
              ? fund.firmDisplay
              : fund.fundName}
          </p>
          <p style={{ fontSize: 12, color: 'var(--ink-4)', marginTop: 3 }}>
            {fund.fundName === 'N/A' || fund.fundName?.startsWith('N/A')
              ? 'Family-owned / corporate — no dedicated fund'
              : `${fund.firmDisplay}${fund.vintage ? ` · Vintage ${fund.vintage}` : ''}`}
          </p>
        </div>

        {/* Metric */}
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <p style={{ fontSize: 22, fontWeight: 700, color: metric.valueColor, lineHeight: 1.1 }}>
            {metric.value}
          </p>
          <p style={{ fontSize: 11, color: 'var(--ink-4)', marginTop: 2 }}>{metric.label}</p>
        </div>

        <div style={{ flexShrink: 0, color: 'var(--ink-5)', marginTop: 4 }}>
          {open ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </div>
      </div>

      {/* ── Progress bar ────────────────────────────────────────────────────── */}
      <div style={{
        height: 10, borderRadius: 5, background: '#F3F4F6',
        overflow: 'hidden', display: 'flex', marginBottom: 10,
      }}>
        {fund.isEstimated ? (
          // Have committed + vintage estimate → show full breakdown
          <>
            <div style={{ width: `${deployedFrac * 100}%`, background: COLOR_DEPLOYED, height: '100%', flexShrink: 0 }} />
            {reservesFrac > 0 && (
              <div style={{ width: `${reservesFrac * 100}%`, background: COLOR_RESERVES, height: '100%', flexShrink: 0 }} />
            )}
            <div style={{ flex: 1, background: COLOR_DRY_POWDER, height: '100%' }} />
          </>
        ) : fund.hasSize ? (
          // Have committed size but no deployment estimate → show ISP strip only
          <>
            {ispFrac > 0 && (
              <div style={{ width: `${ispFrac * 100}%`, background: COLOR_DEPLOYED, height: '100%', flexShrink: 0, minWidth: 4 }} />
            )}
            <div style={{ flex: 1, background: COLOR_DRY_POWDER, height: '100%' }} />
          </>
        ) : (
          // No fund size → ISP-only bar (scale is relative)
          <div style={{ width: `${Math.min(ispFrac * 100, 80)}%`, background: COLOR_DEPLOYED, height: '100%', minWidth: fund.ispDeployedM > 0 ? 6 : 0 }} />
        )}
      </div>

      {/* ── Stats row ───────────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', flexWrap: 'wrap', rowGap: 4, columnGap: 12, fontSize: 12, color: 'var(--ink-3)', alignItems: 'baseline' }}>
        {fund.committedM != null ? (
          <>
            <span>
              <span style={{ fontWeight: 600, color: 'var(--ink-2)' }}>Committed {fmtM(fund.committedM)}</span>
            </span>
            {fund.estDeployedM != null && (
              <>
                <span style={{ color: 'var(--ink-5)' }}>·</span>
                <span>
                  Deployed {fmtM(fund.estDeployedM, true)}
                  {' '}({Math.round(fund.deployedPct * 100)}% est.)
                </span>
              </>
            )}
            {fund.estReservesM != null && (
              <>
                <span style={{ color: 'var(--ink-5)' }}>·</span>
                <span>Reserves {fmtM(fund.estReservesM, true)}</span>
              </>
            )}
          </>
        ) : (
          <span style={{ color: '#D97706', fontWeight: 500 }}>⚠ Fund size not in EDGAR</span>
        )}
        {fund.deals.length > 0 && (
          <>
            <span style={{ color: 'var(--ink-5)' }}>·</span>
            <span style={{ color: '#B8744F', fontWeight: 500 }}>
              ISP {fmtM(fund.ispDeployedM)} tracked
            </span>
            <span style={{ color: 'var(--ink-5)' }}>·</span>
            <span>{fund.deals.length} deal{fund.deals.length !== 1 ? 's' : ''}</span>
          </>
        )}
      </div>

      {/* ── Expanded section ─────────────────────────────────────────────────── */}
      {open && (
        <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px solid rgba(0,0,0,0.06)' }}>

          {/* CalPERS LP position */}
          {fund.calpersData && (
            <div style={{
              background: 'rgba(0,157,140,0.04)',
              border: '1px solid rgba(0,157,140,0.15)',
              borderRadius: 8, padding: '10px 14px', marginBottom: 12,
            }}>
              <p style={{ fontSize: 11, fontWeight: 600, color: '#007a6e', marginBottom: 8 }}>
                CalPERS LP position · {fund.calpersData.fundName}
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px 20px' }}>
                {[
                  ['Committed', fund.calpersData.committed != null ? fmtB(fund.calpersData.committed) : null],
                  ['Called',    fund.calpersData.called    != null ? fmtB(fund.calpersData.called)    : null],
                  ['NAV',       fund.calpersData.nav       != null ? fmtB(fund.calpersData.nav)       : null],
                  ['TVPI',      fund.calpersData.tvpi      != null ? `${fund.calpersData.tvpi.toFixed(2)}x` : null],
                  ['IRR',       fund.calpersData.irr       != null ? `${fund.calpersData.irr.toFixed(1)}%`  : null],
                ].filter(([, v]) => v != null).map(([label, value]) => (
                  <div key={label}>
                    <p style={{ fontSize: 10, color: 'var(--ink-5)', marginBottom: 2 }}>{label}</p>
                    <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-1)' }}>{value}</p>
                  </div>
                ))}
              </div>
              <p style={{ fontSize: 10, color: 'var(--ink-5)', marginTop: 8, lineHeight: 1.5 }}>
                CalPERS LP stake only — not total fund figures. Called% used as proxy to estimate overall deployment pace.
              </p>
            </div>
          )}

          {/* ISP deal list */}
          {fund.deals.length > 0 && (
            <div style={{ marginBottom: 12 }}>
              <p style={{
                fontSize: 10, fontWeight: 700, color: 'var(--ink-4)',
                textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6,
              }}>
                ISP deals in tracker
              </p>
              {fund.deals
                .sort((a, b) => new Date(b.date) - new Date(a.date))
                .map(d => (
                  <button
                    key={d.id}
                    onClick={e => { e.stopPropagation(); onNavigate?.(d.id) }}
                    style={{
                      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                      width: '100%', textAlign: 'left', padding: '5px 8px', borderRadius: 6,
                      background: 'none', border: 'none', cursor: 'pointer',
                      fontSize: 12, color: 'var(--ink-2)',
                    }}
                    onMouseEnter={e => e.currentTarget.style.background = 'rgba(88,114,224,0.06)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'none'}
                  >
                    <span style={{ display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 }}>
                      <span style={{
                        width: 7, height: 7, borderRadius: 2, flexShrink: 0,
                        background: SECTOR_CFG[d.sector]?.color ?? '#aeaeb2',
                      }} />
                      <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {d.acquirerName} → {d.targetName}
                      </span>
                      <span style={{ color: 'var(--ink-5)', flexShrink: 0 }}>
                        {d.date?.slice(0, 7)}
                      </span>
                    </span>
                    <span style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0, marginLeft: 12 }}>
                      <span style={{ fontVariantNumeric: 'tabular-nums', fontWeight: 600 }}>
                        {fmtB(d.dealValue)}
                      </span>
                      <ExternalLink size={10} style={{ color: 'var(--ink-5)' }} />
                    </span>
                  </button>
                ))}
            </div>
          )}

          {/* Form D reference */}
          {fund.formDData && (
            <p style={{ fontSize: 11, color: 'var(--ink-5)', lineHeight: 1.6, marginBottom: 10 }}>
              <span style={{ fontWeight: 600, color: 'var(--ink-4)' }}>EDGAR Form D · </span>
              {fund.formDData.entityName?.replace(/\s+\(CIK[^)]+\)/g, '')} ·{' '}
              {fmtB(fund.formDData.totalAmountSold)} raised ·{' '}
              {fund.formDData.numberOfInvestors} investors ·{' '}
              filed {fund.formDData.filingDate}
              {fund.formDData.filingUrl && (
                <a
                  href={fund.formDData.filingUrl}
                  target="_blank" rel="noopener noreferrer"
                  style={{ color: '#5872E0', marginLeft: 8, fontWeight: 500 }}
                >
                  View on EDGAR ↗
                </a>
              )}
            </p>
          )}

          {/* Estimation note */}
          {fund.isEstimated && (
            <div style={{
              padding: '8px 12px', background: '#FFFBEB',
              borderRadius: 7, fontSize: 11, color: '#92400e', lineHeight: 1.5,
            }}>
              <strong>Deployment estimate</strong>: vintage {fund.vintage} fund, age ~{2026 - fund.vintage} yr →{' '}
              ~{Math.round(fund.deployedPct * 100)}% deployed (industry curve).
              10% reserved for follow-ons. Replace with actual GP/LP data for accuracy.
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ── Sector Lean Panel ─────────────────────────────────────────────────────────

function SectorLeanPanel({ sectorData }) {
  const total = sectorData.reduce((s, x) => s + x.value, 0)

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div style={{
        background: '#fff', borderRadius: 12,
        border: '1px solid rgba(0,0,0,0.07)', padding: '20px',
      }}>
        <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--ink-1)', marginBottom: 4 }}>Sector lean</h3>
        <p style={{ fontSize: 12, color: 'var(--ink-3)', marginBottom: 18 }}>
          ISP deal value by sector across all PE-backed transactions
        </p>

        {/* Segmented bar */}
        <div style={{
          display: 'flex', borderRadius: 8, overflow: 'hidden',
          height: 44, marginBottom: 20, border: '1px solid rgba(0,0,0,0.06)',
        }}>
          {sectorData.map(s => (
            <div
              key={s.name}
              title={`${s.name}: ${fmtB(s.value)} (${(s.pct * 100).toFixed(0)}%)`}
              style={{
                flex: s.pct,
                background: SECTOR_CFG[s.name]?.color ?? '#aeaeb2',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                color: '#fff', fontSize: 13, fontWeight: 600,
                overflow: 'hidden', minWidth: s.pct > 0.08 ? 36 : 0,
              }}
            >
              {s.pct > 0.07 ? `${(s.pct * 100).toFixed(0)}%` : ''}
            </div>
          ))}
        </div>

        {/* Sector rows */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {sectorData.map(s => (
            <div key={s.name} style={{
              background: 'rgba(0,0,0,0.02)',
              borderRadius: 10, border: '1px solid rgba(0,0,0,0.05)', padding: '14px 16px',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                  <span style={{ width: 10, height: 10, borderRadius: 2, background: SECTOR_CFG[s.name]?.color ?? '#aeaeb2', flexShrink: 0 }} />
                  <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-2)' }}>{s.name}</span>
                </span>
                <span style={{ fontSize: 12, color: 'var(--ink-4)', fontVariantNumeric: 'tabular-nums' }}>
                  {(s.pct * 100).toFixed(0)}% of PE book
                </span>
              </div>
              <p style={{ fontSize: 20, fontWeight: 700, color: 'var(--ink-1)' }}>{fmtB(s.value)}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Source notice */}
      <div style={{
        background: '#fff', borderRadius: 12,
        border: '1px solid rgba(0,0,0,0.07)', padding: '16px 20px',
        fontSize: 12, color: 'var(--ink-4)', lineHeight: 1.6,
      }}>
        <p style={{ fontWeight: 600, color: 'var(--ink-3)', marginBottom: 6 }}>Data sources</p>
        {FUND_DATA.lpPortalRefs.slice(0, 4).map(r => (
          <p key={r.name} style={{ marginBottom: 4 }}>
            <span style={{ fontWeight: 500, color: 'var(--ink-3)' }}>• {r.name} </span>
            <span style={{ color: 'var(--ink-5)', fontSize: 11 }}>({r.cadence})</span>
          </p>
        ))}
        <p style={{ marginTop: 8, color: 'var(--ink-5)', fontSize: 11 }}>
          Run <code style={{ background: 'rgba(0,0,0,0.05)', padding: '1px 4px', borderRadius: 3 }}>
            npm run fund-data
          </code> to refresh from EDGAR + CalPERS.
        </p>
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function FundMgmtPage({ deals, onNavigateToDeal }) {
  const funds      = useMemo(() => buildFundRows(deals), [deals])
  const sectorData = useMemo(() => buildSectorLean(deals), [deals])

  const kpi = useMemo(() => {
    const sized       = funds.filter(f => f.hasSize)
    const totalSize   = sized.reduce((s, f) => s + (f.committedM ?? 0), 0)
    const totalDry    = funds.filter(f => f.estDryPwdrM != null).reduce((s, f) => s + f.estDryPwdrM, 0)
    const totalISP    = [...new Map(funds.flatMap(f => f.deals).map(d => [d.id, d])).values()]
                          .reduce((s, d) => s + (d.dealValue ?? 0), 0)
    const withCalPERS = funds.filter(f => f.calpersData).length
    return { fundCount: funds.length, sizedCount: sized.length, totalSize, totalDry, totalISP, withCalPERS }
  }, [funds])

  return (
    <div className="flex-1 overflow-y-auto scroll-area" style={{ background: 'var(--page-bg)' }}>
      <div style={{ maxWidth: 1400, margin: '0 auto', padding: '24px 28px', display: 'flex', flexDirection: 'column', gap: 20 }}>

        {/* Data notice */}
        <div style={{
          display: 'flex', alignItems: 'flex-start', gap: 10,
          background: '#FEF3C7', border: '1px solid #FDE68A',
          borderRadius: 10, padding: '10px 16px', fontSize: 12, color: '#92400e',
        }}>
          <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1.5 }} />
          <p>
            <strong>Fund sizes</strong> from SEC EDGAR Form D where available.{' '}
            <strong>Deployment</strong> estimated by vintage-year curve — not actual GP data.{' '}
            ISP column shows tracked deals only (understates real deployment).{' '}
            For actual called/NAV/distributions, run <code style={{ background: 'rgba(0,0,0,0.08)', padding: '1px 4px', borderRadius: 3 }}>npm run fund-data</code>{' '}
            and supplement with Infralogic, LP portals (CalPERS, WSIB, Oregon Treasury), or GP reports.
          </p>
        </div>

        {/* KPI row */}
        <div style={{ display: 'flex', gap: 14 }}>
          <KPICard
            title="Funds tracked"
            value={kpi.fundCount}
            sub={`${kpi.sizedCount} with EDGAR fund size · ${kpi.withCalPERS} with CalPERS data`}
          />
          <KPICard
            title="Total fund capital (EDGAR)"
            value={fmtM(kpi.totalSize)}
            sub={`${kpi.sizedCount} funds with Form D closing amounts`}
            badge="Partial — non-EDGAR funds excluded"
          />
          <KPICard
            title="Est. dry powder"
            value={kpi.totalDry > 0 ? fmtM(kpi.totalDry, true) : '—'}
            sub="Vintage-curve estimate, sized funds only"
            badge="Estimated — source GP/LP data for accuracy"
          />
          <KPICard
            title="ISP deployed (tracked)"
            value={fmtB(kpi.totalISP)}
            sub="Aggregate ISP deal value in tracker"
            badge="Understates actual deployment"
          />
        </div>

        {/* Bar legend */}
        <div style={{
          display: 'flex', flexWrap: 'wrap', gap: 20, fontSize: 12,
          background: '#fff', borderRadius: 10, border: '1px solid rgba(0,0,0,0.07)',
          padding: '11px 18px', alignItems: 'center',
        }}>
          {[
            [COLOR_DEPLOYED,   'Est. deployed'],
            [COLOR_RESERVES,   'Est. reserves (10%)'],
            [COLOR_DRY_POWDER, 'Est. dry powder'],
          ].map(([color, label]) => (
            <span key={label} style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
              <span style={{ width: 28, height: 8, borderRadius: 4, background: color,
                border: color === COLOR_DRY_POWDER ? '1px solid #d1d5db' : 'none', flexShrink: 0 }} />
              <span style={{ color: 'var(--ink-3)' }}>{label}</span>
            </span>
          ))}
          <span style={{ marginLeft: 'auto', color: 'var(--ink-5)', fontSize: 11 }}>
            Deployment % by vintage year · fund size from EDGAR Form D
          </span>
        </div>

        {/* Main grid: fund list + sector lean */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 20, alignItems: 'start' }}>

          {/* Fund list */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {funds.map(fund => (
              <FundCard
                key={fund.key}
                fund={fund}
                onNavigate={onNavigateToDeal}
              />
            ))}
          </div>

          {/* Right: sector lean */}
          <SectorLeanPanel sectorData={sectorData} />

        </div>
      </div>
    </div>
  )
}
